## YAML Template.
spring:
  application:
    name: quotes-redis
server:
  port: 5054
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:5051/eureka}
  instance:
    preferIpAddress: true
